name: build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'
    branches:
      - 'main'
      - 'release/**'
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx8g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-    
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test with Gradle
        run: ./gradlew licensee :wrapper:publishToMavenLocal
